// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/tasks": {
            "get": {
                "description": "Get all tasks",
                "tags": [
                    "Task"
                ],
                "summary": "Get all tasks",
                "responses": {}
            },
            "post": {
                "description": "Create a new task",
                "tags": [
                    "Task"
                ],
                "summary": "Create a New Task",
                "responses": {}
            }
        },
        "/tasks/{id}": {
            "get": {
                "description": "Get a task by ID",
                "tags": [
                    "Task"
                ],
                "summary": "Get task by ID",
                "responses": {}
            },
            "put": {
                "description": "Update an existing task",
                "tags": [
                    "Task"
                ],
                "summary": "Update an existing task",
                "responses": {}
            },
            "delete": {
                "description": "Delete a task by ID",
                "tags": [
                    "Task"
                ],
                "summary": "Delete a task",
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
