info:
  contact: {}
paths:
  /tasks:
    get:
      description: Get all tasks
      responses: {}
      summary: Get all tasks
      tags:
      - Task
    post:
      description: Create a new task
      responses: {}
      summary: Create a New Task
      tags:
      - Task
  /tasks/{id}:
    delete:
      description: Delete a task by ID
      responses: {}
      summary: Delete a task
      tags:
      - Task
    get:
      description: Get a task by ID
      responses: {}
      summary: Get task by ID
      tags:
      - Task
    put:
      description: Update an existing task
      responses: {}
      summary: Update an existing task
      tags:
      - Task
swagger: "2.0"
